spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
      #format_sql: true

resilience4j.rateLimiter:
  configs:
    default:
      timeoutDuration: 5s
      limitRefreshPeriod: 20s
      limitForPeriod: 3

logging:
  level:
    root: info
    ru.otus.hw: debug

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true