spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

mongock:
  runner-type: "ApplicationRunner"
  change-logs-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
      diskspace:
        enabled: true
    defaults:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 10
        failureRateThreshold: 3
        waitDurationInOpenState: 2s
        minimumNumberOfCalls: 3

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              ReactiveMongoTemplate: DEBUG